### ISSUE TITLE
DefinitionFinder\ParseException for aws-sdk-php

### ISSUE THREAD

**Issue by eryi** [fredemmott/hhvm-autoload#10]
# How to reproduce
    require aws/aws-sdk-php:3.20.10

# Error thrown
````
[FredEmmott\DefinitionFinder\ParseException]                                 
  /home/nonroot/app/src/vendor/aws/aws-sdk-php/src/Api/DocModel.php:106: Don'  
  t understand public/private/protected outside of a class at line 106 
````

# Link to file
https://github.com/aws/aws-sdk-php/blob/master/src/Api/DocModel.php#L106

**Comment by fredemmott** [comment]
@eryi: can you file this over at https://github.com/fredemmott/definition-finder/issues ? thanks!
